#!/usr/bin/env python3
"""
MetaQuest Professional Reporting Module - Base Classes v4.0.0
Enhanced for three-tier pathogen risk assessment
*** REFACTORED to use global OutputFormatter ***
"""

import json
from abc import ABC, abstractmethod
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional
from ..io.output_formatter import get_formatter  # <-- IMPORT FORMATTER

class BaseReporter(ABC):
    """
    Base class for all MetaQuest report generators.
    Provides standardized formatting and logging for scientific reports.
    """
    
    VERSION = "4.0.0"
    ORGANIZATION = "MetaQuest Metagenomics Team"
    LINE_WIDTH = 70  # Optimized for readability
    
    def __init__(self, output_dir: Path):
        """
        Initialize base report generator.
        
        Args:
            output_dir: Directory for report output
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.timestamp = datetime.now()
        
        # Setup formatter
        self.formatter = get_formatter()
    
    def print_section_header(self, title: str):
        """Print a section header using the formatter."""
        self.formatter.section_header(title)
    
    def print_subsection(self, title: str):
        """Print a subsection header using the formatter."""
        self.formatter.info(f"\n{title}")
        self.formatter.info(f"{'-' * len(title)}")
    
    def format_header(self, title: str) -> List[str]:
        """Create professional report header."""
        lines = [
            "=" * self.LINE_WIDTH,
            self._center_text(title.upper()),
            "=" * self.LINE_WIDTH,
            "",
            f"Generated: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}",
            f"Pipeline Version: MetaQuest v{self.VERSION}",
            "",
            "-" * self.LINE_WIDTH,
        ]
        return lines
    
    def format_footer(self) -> List[str]:
        """Create professional report footer."""
        return [
            "",
            "-" * self.LINE_WIDTH,
            "",
            f"Report generated by MetaQuest v{self.VERSION}",
            f"Analysis completed: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}",
            f"Contact: metaquest-support@example.org",
            "",
            "=" * self.LINE_WIDTH,
        ]
    
    def _center_text(self, text: str) -> str:
        """Center text within LINE_WIDTH."""
        padding = (self.LINE_WIDTH - len(text)) // 2
        return " " * padding + text
    
    def format_table(self, headers: List[str], rows: List[List[str]],
                    alignments: Optional[List[str]] = None) -> str:
        """
        Format data as ASCII table.
        (This function returns a string, so no formatter calls needed)
        """
        if not alignments:
            alignments = ['left'] * len(headers)
        
        col_widths = [len(h) for h in headers]
        for row in rows:
            for i, cell in enumerate(row):
                col_widths[i] = max(col_widths[i], len(str(cell)))
        
        col_widths = [w + 2 for w in col_widths]
        
        lines = []
        
        header_line = ""
        for header, width, align in zip(headers, col_widths, alignments):
            if align == 'right':
                header_line += str(header).rjust(width)
            elif align == 'center':
                header_line += str(header).center(width)
            else:
                header_line += str(header).ljust(width)
        lines.append(header_line)
        lines.append("-" * sum(col_widths))
        
        for row in rows:
            row_line = ""
            for cell, width, align in zip(row, col_widths, alignments):
                cell_str = str(cell)
                if align == 'right':
                    row_line += cell_str.rjust(width)
                elif align == 'center':
                    row_line += cell_str.center(width)
                else:
                    row_line += cell_str.ljust(width)
            lines.append(row_line)
        
        return '\n'.join(lines)
    
    def save_report(self, content: str, filename: str) -> Path:
        """
        Save text report to file.
        """
        filepath = Path(filepath)  # Accept Path or str
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        self.formatter.success(f"Report saved to {filepath.name}")
        return filepath
    
    def save_json(self, data: Dict, filepath: Path) -> Path:
        """
        Save JSON data with metadata.
        """
        report_data = {
            'metadata': {
                'generation_timestamp': self.timestamp.isoformat(),
                'pipeline_version': f'MetaQuest v{self.VERSION}',
            },
            'data': data
        }
        
        filepath = Path(filepath)  # Accept Path or str
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report_data, f, indent=2)
        
        self.formatter.success(f"JSON data saved to {filepath.name}")
        return filepath