#!/usr/bin/env python3
"""
MetaQuest Professional Reporting Module - Base Classes v4.0.0
Enhanced for three-tier pathogen risk assessment
"""

import json
import logging
from abc import ABC, abstractmethod
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional


class BaseReporter(ABC):
    """
    Base class for all MetaQuest report generators.
    Provides standardized formatting and logging for scientific reports.
    """
    
    VERSION = "4.0.0"
    ORGANIZATION = "MetaQuest Metagenomics Team"
    LINE_WIDTH = 70  # Optimized for readability
    
    def __init__(self, output_dir: Path):
        """
        Initialize base report generator.
        
        Args:
            output_dir: Directory for report output
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.timestamp = datetime.now()
        
        # Setup logging
        self.logger = logging.getLogger(self.__class__.__name__)
        if not self.logger.handlers:
            handler = logging.StreamHandler()
            formatter = logging.Formatter(
                '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
            )
            handler.setFormatter(formatter)
            self.logger.addHandler(handler)
            self.logger.setLevel(logging.INFO)
    
    def print_section_header(self, title: str):
        """Print a section header for console output."""
        print("\n" + "=" * self.LINE_WIDTH)
        print(f"  {title}")
        print("=" * self.LINE_WIDTH)
    
    def print_subsection(self, title: str):
        """Print a subsection header."""
        print(f"\n{title}")
        print("-" * len(title))
    
    def format_header(self, title: str) -> List[str]:
        """Create professional report header."""
        lines = [
            "=" * self.LINE_WIDTH,
            self._center_text(title.upper()),
            "=" * self.LINE_WIDTH,
            "",
            f"Generated: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}",
            f"Pipeline Version: MetaQuest v{self.VERSION}",
            "",
            "-" * self.LINE_WIDTH,
        ]
        return lines
    
    def format_footer(self) -> List[str]:
        """Create professional report footer."""
        return [
            "",
            "-" * self.LINE_WIDTH,
            "",
            f"Report generated by MetaQuest v{self.VERSION}",
            f"Analysis completed: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}",
            f"Contact: metaquest-support@example.org",
            "",
            "=" * self.LINE_WIDTH,
        ]
    
    def _center_text(self, text: str) -> str:
        """Center text within LINE_WIDTH."""
        padding = (self.LINE_WIDTH - len(text)) // 2
        return " " * padding + text
    
    def format_table(self, headers: List[str], rows: List[List[str]],
                    alignments: Optional[List[str]] = None) -> str:
        """
        Format data as ASCII table.
        
        Args:
            headers: Column headers
            rows: Data rows
            alignments: 'left', 'right', or 'center' for each column
        
        Returns:
            Formatted table string
        """
        if not alignments:
            alignments = ['left'] * len(headers)
        
        # Calculate column widths
        col_widths = [len(h) for h in headers]
        for row in rows:
            for i, cell in enumerate(row):
                col_widths[i] = max(col_widths[i], len(str(cell)))
        
        # Add padding
        col_widths = [w + 2 for w in col_widths]
        
        # Build table
        lines = []
        
        # Header
        header_line = ""
        for header, width, align in zip(headers, col_widths, alignments):
            if align == 'right':
                header_line += str(header).rjust(width)
            elif align == 'center':
                header_line += str(header).center(width)
            else:
                header_line += str(header).ljust(width)
        lines.append(header_line)
        lines.append("-" * sum(col_widths))
        
        # Rows
        for row in rows:
            row_line = ""
            for cell, width, align in zip(row, col_widths, alignments):
                cell_str = str(cell)
                if align == 'right':
                    row_line += cell_str.rjust(width)
                elif align == 'center':
                    row_line += cell_str.center(width)
                else:
                    row_line += cell_str.ljust(width)
            lines.append(row_line)
        
        return '\n'.join(lines)
    
    def save_report(self, content: str, filename: str) -> Path:
        """
        Save text report to file.
        
        Args:
            content: Report content
            filename: Output filename
        
        Returns:
            Path to saved file
        """
        filepath = self.output_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        self.logger.info(f"Report saved to {filepath}")
        return filepath
    
    def save_json(self, data: Dict, filename: str) -> Path:
        """
        Save JSON data with metadata.
        
        Args:
            data: Data dictionary
            filename: Output filename
        
        Returns:
            Path to saved file
        """
        report_data = {
            'metadata': {
                'generation_timestamp': self.timestamp.isoformat(),
                'pipeline_version': f'MetaQuest v{self.VERSION}',
            },
            'data': data
        }
        
        filepath = self.output_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report_data, f, indent=2)
        
        self.logger.info(f"JSON data saved to {filepath}")
        return filepath
