#!/usr/bin/env python3
"""
MetaQuest Professional Reporting Module - Base Classes
Author: MetaQuest Metagenomics Team
License: MIT
"""

import json
from abc import ABC, abstractmethod
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional


class BaseReportGenerator(ABC):
    """
    Base class for all MetaQuest report generators with professional formatting.
    
    This class provides standardized methods for creating scientific reports
    with consistent headers, footers, and formatting conventions.
    """
    
    VERSION = "3.6.0"
    ORGANIZATION = "MetaQuest Metagenomics Team"
    LINE_WIDTH = 100
    
    def __init__(self, output_dir: Path, analysis_type: str):
        """
        Initialize base report generator.
        
        Args:
            output_dir: Directory for report output
            analysis_type: Type of analysis being reported
        """
        self.output_dir = Path(output_dir)
        self.analysis_type = analysis_type
        self.timestamp = datetime.now()
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    @abstractmethod
    def generate_report(self, data: Any, **kwargs) -> Dict[str, str]:
        """
        Generate the specific report type.
        
        Args:
            data: Input data for report generation
            **kwargs: Additional parameters
            
        Returns:
            Dictionary containing paths to generated reports
        """
        pass
    
    def _create_header(self, title: str, tool_info: str = None, 
                      database_info: str = None) -> List[str]:
        """
        Create professional scientific report header.
        
        Args:
            title: Report title
            tool_info: Tool and version information
            database_info: Database information
            
        Returns:
            List of header lines
        """
        header_lines = [
            "=" * self.LINE_WIDTH,
            self._center_text(title),
            "=" * self.LINE_WIDTH,
            "",
            f"Generated: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"Analysis Type: {self.analysis_type}",
            f"Pipeline Version: MetaQuest v{self.VERSION}",
        ]
        
        if tool_info:
            header_lines.append(f"Classification Tool: {tool_info}")
        
        if database_info:
            header_lines.append(f"Reference Database: {database_info}")
        
        header_lines.extend([
            f"Report ID: MQ_{self.analysis_type.upper().replace(' ', '_')}_{self.timestamp.strftime('%Y%m%d_%H%M%S')}",
            "",
            "-" * self.LINE_WIDTH,
            ""
        ])
        
        return header_lines
    
    def _create_footer(self) -> List[str]:
        """
        Create professional report footer.
        
        Returns:
            List of footer lines
        """
        return [
            "",
            "-" * self.LINE_WIDTH,
            "",
            "REPORT INFORMATION",
            f"Analysis completed: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}",
            f"Generated by: MetaQuest Pipeline v{self.VERSION}",
            f"Organization: {self.ORGANIZATION}",
            "",
            "CITATION",
            "If you use MetaQuest in your research, please cite:",
            "MetaQuest: A comprehensive metagenomics analysis pipeline",
            "Contact: support@metaquest.org | Documentation: https://docs.metaquest.org",
            "",
            "=" * self.LINE_WIDTH,
            f"{self._center_text('End of Report')}",
            "=" * self.LINE_WIDTH
        ]
    
    def _create_section_header(self, title: str, level: int = 1) -> List[str]:
        """
        Create section header with appropriate formatting.
        
        Args:
            title: Section title
            level: Header level (1=major, 2=minor, 3=subsection)
            
        Returns:
            List of header lines
        """
        if level == 1:
            return [
                "",
                "=" * self.LINE_WIDTH,
                self._center_text(title.upper()),
                "=" * self.LINE_WIDTH,
                ""
            ]
        elif level == 2:
            return [
                "",
                title.upper(),
                "-" * len(title),
                ""
            ]
        else:  # level 3
            return [
                "",
                f"• {title}",
                ""
            ]
    
    def _center_text(self, text: str) -> str:
        """Center text within LINE_WIDTH."""
        padding = (self.LINE_WIDTH - len(text)) // 2
        return " " * padding + text
    
    def _format_table(self, headers: List[str], rows: List[List[str]], 
                     alignments: Optional[List[str]] = None) -> List[str]:
        """
        Format data as a professional table.
        
        Args:
            headers: Column headers
            rows: Data rows
            alignments: Column alignments ('left', 'right', 'center')
            
        Returns:
            List of formatted table lines
        """
        if not alignments:
            alignments = ['left'] * len(headers)
        
        # Calculate column widths
        col_widths = [len(h) for h in headers]
        for row in rows:
            for i, cell in enumerate(row):
                col_widths[i] = max(col_widths[i], len(str(cell)))
        
        # Add padding
        col_widths = [w + 2 for w in col_widths]
        
        # Format header
        table_lines = []
        header_line = ""
        for i, (header, width, align) in enumerate(zip(headers, col_widths, alignments)):
            if align == 'right':
                header_line += str(header).rjust(width)
            elif align == 'center':
                header_line += str(header).center(width)
            else:
                header_line += str(header).ljust(width)
        
        table_lines.append(header_line)
        table_lines.append("-" * sum(col_widths))
        
        # Format rows
        for row in rows:
            row_line = ""
            for i, (cell, width, align) in enumerate(zip(row, col_widths, alignments)):
                cell_str = str(cell)
                if align == 'right':
                    row_line += cell_str.rjust(width)
                elif align == 'center':
                    row_line += cell_str.center(width)
                else:
                    row_line += cell_str.ljust(width)
            table_lines.append(row_line)
        
        return table_lines
    
    def _format_statistics(self, stats: Dict[str, Any], 
                          title: str = "Statistical Summary") -> List[str]:
        """
        Format statistical data professionally.
        
        Args:
            stats: Dictionary of statistics
            title: Section title
            
        Returns:
            List of formatted lines
        """
        lines = [title, "-" * len(title), ""]
        
        for key, value in stats.items():
            formatted_key = key.replace('_', ' ').title()
            if isinstance(value, float):
                lines.append(f"{formatted_key}: {value:.4f}")
            elif isinstance(value, int):
                lines.append(f"{formatted_key}: {value:,}")
            else:
                lines.append(f"{formatted_key}: {value}")
        
        return lines
    
    def _save_text_report(self, content: List[str], filename: str) -> str:
        """
        Save text report with standard formatting.
        
        Args:
            content: Report content lines
            filename: Output filename
            
        Returns:
            Full path to saved file
        """
        filepath = self.output_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write('\n'.join(content))
        return str(filepath)
    
    def _save_json_report(self, data: Dict, filename: str) -> str:
        """
        Save JSON report with metadata.
        
        Args:
            data: Report data dictionary
            filename: Output filename
            
        Returns:
            Full path to saved file
        """
        report_data = {
            'metadata': {
                'analysis_type': self.analysis_type,
                'generation_timestamp': self.timestamp.isoformat(),
                'pipeline_version': f'MetaQuest v{self.VERSION}',
                'organization': self.ORGANIZATION
            },
            'data': data
        }
        
        filepath = self.output_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report_data, f, indent=2, ensure_ascii=False)
        
        return str(filepath)
    
    def _format_percentage(self, value: float, decimals: int = 2) -> str:
        """Format percentage with consistent precision."""
        return f"{value:.{decimals}f}%"
    
    def _format_scientific(self, value: float, decimals: int = 2) -> str:
        """Format number in scientific notation."""
        return f"{value:.{decimals}e}"
    
    def _create_summary_box(self, title: str, items: List[str]) -> List[str]:
        """
        Create a visually distinct summary box.
        
        Args:
            title: Box title
            items: List of summary items
            
        Returns:
            List of formatted lines
        """
        box_width = self.LINE_WIDTH - 4
        lines = [
            "┌" + "─" * (box_width - 2) + "┐",
            "│ " + title.center(box_width - 4) + " │",
            "├" + "─" * (box_width - 2) + "┤"
        ]
        
        for item in items:
            # Wrap long lines
            if len(item) > box_width - 6:
                words = item.split()
                current_line = ""
                for word in words:
                    if len(current_line) + len(word) + 1 <= box_width - 6:
                        current_line += word + " "
                    else:
                        lines.append("│ " + current_line.ljust(box_width - 4) + " │")
                        current_line = word + " "
                if current_line:
                    lines.append("│ " + current_line.ljust(box_width - 4) + " │")
            else:
                lines.append("│ " + item.ljust(box_width - 4) + " │")
        
        lines.append("└" + "─" * (box_width - 2) + "┘")
        
        return lines